{% set version = "0.1.4" %}

package:
    name: f90wrap
    version: {{ version }}

source:
    fn: f90wrap-{{ version }}.tar.gz
    url: https://github.com/jameskermode/f90wrap/releases/tag/v{{ version }}

build:
    number: 0
    skip: True  # [win or osx]
    script:
        - python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - numpy x.x
        - gcc
    run:
        - python
        - numpy x.x
        - libgcc  # [linux]
        - libgfortran  # [osx]

test:
    imports:
        - f90wrap
    commands:
        - f90wrap -h
        - f2py-f90wrap -h

about:
    home: https://github.com/jameskermode/f90wrap
    license: GPL-2.0
    summary: Fortran to Python interface generator with derived type support

extra:
    recipe-maintainers:
        - jameskermode
        - ocefpaf
