travis:
  secure:
    BINSTAR_TOKEN: qdH+cXC0ePyxmqILnJEglAU0YEwunIqzBXHc8tEgCvZGCgybGb4d44QEBsuER8l1VBqRtQh9mjfof+ElWYhsJarmjxXcnAK+LytWrRn7FvdQjrEgHZTcXOua77iTVGNTsK0r91/YbutT+spmRIec/KJOP2gmaDKHYh9gAnwJA6ITqbs851OoRxY7hgEaDCt/9XQutjs/cD5FDkWBfpUqY3++8mOkmIewQ6E4SOoeFdz3G40hBf6r4FtwD47zSM4Xg6Z442ZoGMlFY6fg9SedwB/fXZ8zRv578QyQlZQFtYDD44zflIHWrGhTAztLRtaCQdrcmeB/xIIqbXKcSvF9mPK7AUSUw5AquXIwKA8tOOPoEwz79qoK2YAauITbHtC0Mys/u08cN/ZbuSD3JRCWxF1wjlPpVL7HMPROyGM46gDeA0Q5yR2Y+pWufZSPC2WnjFIf4fPCMmOLJ8/FTFON2Hc8dtINKmdVPgPjSiRuQiszsiGFCFWm7CsNQFAZKYMhNvrbaqrsvVElFvMoPs1Mjmmgj2KD79c29wX4dHj0ARNOTBHzvQDimc0GbW3ruuL4XqakLv9tPRBj6elmGT7LiM2WeXfXFTtUBcl4vIU7CE9kYENL9gVcfxDN19/L9r/nSRsd1JZNYxJp19OU5gjh1jmnt+9z56Cx06+PczwjGGg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
